services:
  - type: web
    name: fleetcart
    env: docker
    plan: free
    buildCommand: "./render-build.sh"
    startCommand: "./render-start.sh"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: errorlog
      - key: CACHE_DRIVER
        value: database
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database

databases:
  - name: fleetcart-db
    plan: free